% [base_seq,fol_seq] = sim_rmod_resp(tree_adress,seq_len, rmod)
%
% DESCRIPTION: The function generates a sequence following the structure of
% the tree discribed in tree_adress and a corresponding response sequence
% that can be generated by maximizing or emulating the probabilities in the
% non-deterministic contexts
%
% INPUT:
%
% tree_adress = adress to the .tree file containing the contex tree
% structure.
% seq_len = requested length for the sequence.
% rmod = if set 1, the response sequence will use the maximization
% strategy, if set to 0 it will emulates the probabilities according to the
% structure of the context tree
%
% OUTPUT:
%
% base_seq = sequence following the structure of the tree discribed in the
% .tree file of <tree_adress>
% fol_seq = corresponding response sequence to the <base_seq>
%
% Comment:  You will find example parameters in the body of the function
% that you can use as input to understand function functionality
%
% AUTHOR: Paulo Roberto Cabral Passos  DATE: 24/02/2025

function [base_seq,fol_seq] = sim_rmod_resp(tree_adress,seq_len, rmod)

% EXAMPLE PARAMETERS FOR TESTING THE FUNCTION
% rmod = 0;
% tree_adress = 'C:\Users\Cabral\Documents\pos_doc\Publications\Passos_etal202X\files_for_reference\num7.tree'; 
% seq_len = 100;

[tree, PM] = build_treePM(tree_adress);
alphabet = get_tree_alphabet(tree);
cPM = cumulative_PM(PM);
tree_h = get_treelength(tree);
% Input validation
if seq_len < tree_h
   disp('Sequence length must be larger the the tree height.')
   return
end
seq_len = seq_len + tree_h;

base_seq = gen_tree_sequence(tree,PM,seq_len);

fol_seq = zeros(1,seq_len);

for a = 1:length(base_seq)
   got_it = 0;
    for b = 1:tree_h
        if (a - b + 1) > 0
           cur_vec = base_seq(a-b+1:a);
            for c = 1:length(tree)
                if isequal(cur_vec,tree{1,c})
                   got_it = 1;
                   if rmod == 0
                       proxy = rand();
                       for d = 1:length( cPM(c,:) )
                           if proxy <= cPM(c,d)
                                if (a+1) <= length(fol_seq)
                                   fol_seq(1,a+1) = alphabet(d);
                                   break;
                                end              
                           end
                       end                   
                   else
                       if (a+1) <=length(fol_seq)
                           [~,i_max] = max( PM(c,:) );
                           fol_seq(1,a+1) = alphabet(i_max);
                       end                                      
                   end
                   break;
                end
            end      
        end
        if got_it == 1 
           break;
        else
           if (a + 1) <= length(fol_seq)
              fol_seq(1,a+1) = alphabet(randi([1,length(alphabet)]));
           end
        end
    end
end

base_seq = base_seq(tree_h+1:end);
fol_seq = fol_seq(tree_h+1:end);

end